blog_project/urls.py
from django.contrib import admin
from django.urls import path , include
from post import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView , LogoutView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Home.as_view() ,name='home'),
    path('post/',include('post.urls',namespace='Post')),
    path('comment/',include('comment.urls',namespace='Comment')),
    path('signup/',views.SignupView.as_view(),name='signup'),
    path('login/',LoginView.as_view(template_name='registrations/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),    
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path , include 
from comment import views 
app_name = 'Comment'

urlpatterns =[
path('add-comment/<int:pk>/', views.CreateComment.as_view(), name='add_comment'),
]

post/urls.py
from post import views 
from django.urls import path , include 
app_name = 'Post'
urlpatterns =[
path('post-create/',views.PostCreat.as_view(),name='create'),
path('post-edit/<int:pk>',views.PostUpdate.as_view(),name='update'),
path('post-list/',views.PostList.as_view(),name='post_list'),
path('post-detail/<pk>/',views.PostDetail.as_view(),name='detail'),
path('post-delete/<int:pk>/',views.PostDelete.as_view(),name='delete'),
path('publish-post/<int:pk>/',views.publish_post,name='publish'),

]

post/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.conf import settings
from django.utils import timezone
# Create your models here.

# def upload_location(instance, filename):
#     return "%s/%s" %(instance.pk, filename)

class post(models.Model):
    """Post model"""
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=True ,blank=True)
    title = models.CharField(max_length=254)
    publish = models.DateField(null=True , blank=True)
    draft = models.BooleanField(default=False)
    slug = models.SlugField(unique=True)
    image = models.FileField(null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    creat_date = models.DateTimeField(auto_now=False , auto_now_add=True)

    # define representation name of post 
    def __str__(self):
    	return self.title 
    	
    def get_absolute_url(self):
    	return reverse('Post:detail', kwargs={'pk':self.pk})

    
    def post_publish(self):
        self.publish = timezone.now()
        self.save()    


def create_slug(instance , new_slug=None):
     slug = slugify(instance.title)
     if new_slug is not None:
        slug = new_slug
     qs = post.objects.filter(slug=slug).order_by('-slug')
     exist = qs.exists()

     if exist:
        new_slug = "%s-%s" %(slug , qs.first().id)
        return create_slug(instance , new_slug=new_slug)
     return slug       

def pre_save_reciver(sender,instance , *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_reciver ,sender=post)        

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title></title>
<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
<!-- Google Fonts -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<!-- Bootstrap core CSS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
<!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/css/mdb.min.css" rel="stylesheet">
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">


{% block extra_content %}
    
{% endblock extra_content %}

</head>
<body class="">

<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v7.0&appId=172725803951076&autoLogAppEvents=1" nonce="ULRpiNg0"></script>


<!--Navbar -->
<div class="">
  <div class="">
    <nav class="mb-1 navbar navbar-expand-lg navbar-dark default-color">
  <a class="navbar-brand" href="{% url 'Post:post_list' %}" >feelsafe security</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-333"
    aria-controls="navbarSupportedContent-333" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent-333">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
     
      {% if not user.is_authenticated %}
           <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      
      {% endif %}
     
    </ul>
    <ul class="navbar-nav ml-auto nav-flex-icons">
      

      <li class="nav-item">
        <a class="nav-link waves-effect waves-light" href="{% url 'signup' %}">
          <i class="far fa-grin-alt"></i>
         signup
        </a>
      </li>
            {% if user.is_authenticated %}

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          {{user}}
          <i class="fas fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right dropdown-default"
          aria-labelledby="navbarDropdownMenuLink-333">
          <a class="dropdown-item" href="{% url 'Post:create' %}">Add Post</a>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
          <a class="dropdown-item" href="{% url 'Post:post_list' %}">Posts</a>
        </div>
       </li>
{% endif %}
</ul>
</div>
</nav>
</div>
</div>

   {% if messages %}  
<div class="alert alert-dismissible fade show" role="alert">
    <ul class="messages"style="list-style-type: none">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}><p class=" alert">{{ message }}</p></li>
    {% endfor %}
    </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

{% endif %}


<div class="button"><a class="show" href="#">feelsafe</a></div>

<div>
  
  {% block navbar %}
      
  {% endblock navbar %}
</div>


<!-- JQuery -->
<script src="{% static 'pannel.js' %}"></script>
<script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.16.0/js/mdb.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>

<!--  <script type="text/javascript">
  $(document).ready(function(){
    $('.content-markdown').each(function(){
       var content = $(this).text()
       console.log(content)
       var markdown = marked(content)
       console.log(markdown)
       $(this).html(markdown)
    }) 
  })

</script>  -->
<script>var editor = new MediumEditor('.editable');</script>
</body>
</html>

templates/post_create.html
{% extends "base.html" %}
<!-- 
 {% block extra_content %}
  <div class="" style="background-color: white">
        {{form.media}}
   </div> 
{% endblock extra_content %} -->
{% block navbar %}
<div class="container">
    <h1 class="text-center text-capitalize text-dark-60">  <small class="">🤔😶😶{{user}}</small></h1>

    <div class="">
        <form method="post" enctype="multipart/form-data" accept-charset="utf-8">
            {% csrf_token %}
            <section class="form-elegant">
                <!--Form without header-->
                <div class="card">
                    <div class="card-body mx-4">
                        <!--Header-->
                        <!--     <div class="text-center">
        <h3 class="dark-grey-text mb-5"><strong></strong></h3>
      </div> -->
                        <!--Body-->
                        <div class="md-form ">
                            <input name="title" type="text" id="Form-email1" class="form-control">
                            <label for="Form-email1" name="title">title</label>
                        </div>
                        <div class="md-form pb-3">
                    
                            <textarea col="50" rows="20" id="0" name="content" id="Form-pass1" class="form-control border-0"></textarea>
                            <label>Content</label>
                        </div>
                        <input class="btn btn btn-sm btn-danger z-depth-1" type="file" name="image" id="id_image">
                        <div class="text-center mb-3">
                          
                        </div>
                          <button type="submit" class="btn btn-warning z-depth-2">add Post</button>
                    </div>
                </div>
                <!--/Form without header-->
            </section>
        </form>
    </div>
</div>
{% endblock navbar %}

templates/post_delete.html
{% extends "base.html" %}

{% block navbar %}

    <form  method="post" accept-charset="utf-8">
    	{% csrf_token %}
         <div class="container-sm">
         		<h1 class="alert alert-info"> <p> conform delete</p></h1>
    	<button type="submit" class="btn btn-outline-danger">Delete</button>
         </div>
    	
    </form>
{% endblock navbar %}

templates/post_detail.html
{% extends "base.html" %}
{% load urlshr %}

{% block navbar %}
<div class="container-sm ">
    <div class="jumbotron">
      
               {% if post.image %}
                    <img width="350px" height="250px" src="{{post.image.url}}" alt="image">
               
               {% endif %}
        <h2 class="text-secondary">
            <p class="">{{post.title|capfirst}}
                <h4> <small class="text-info"> Updated  {{post.updated|timesince}} 
                    </small>
                </h4>
            </p>
        </h2>

        <div class="text-black-40">
            <div class="editable">
              {{post.content}}
            </div><br>

        </div>

        <div class="">
        <a href="https://www.facebook.com/sharer/sharer.php?u= {{request.build_absolute_uri}}"class="button btn-floating btn-lg btn-fb" type="button" role="button"><i class="fab fa-facebook-f "></i></a>

        <a href="https://twitter.com/home?status=I'{{post.content|urlshr}} {{request.build_absolute_uri}}"class="btn-floating btn-lg btn-tw" type="button" role="button"><i class="fab fa-twitter"></i></a>

        <a href='https://plus.google.com/share?url= {{request.build_absolute_uri}}'class="btn-floating btn-lg btn-gplus" type="button" role="button"><i class="fab fa-google-plus-g"></i></a>
         
        </div>

   <div class="row buttons">
    <a href="{% url 'Post:update' pk=post.pk %}" class="btn  btn-default btn-rounded margin">Update</a>
    <a href="{% url 'Post:delete' pk=post.pk %}" class="btn   btn-danger rounded margin">Delete</a>
   </div>
      <div class="publish-button">
         <p><i class="text-black-60">
           {% if post.publish %}
               published:{{post.publish}}
           
           {% endif %}

         </i></p>
        <a class="btn btn-sm btn-info publish-button" href="{% url 'Post:publish' pk=post.pk %}"> publish</a>
      </div>
     
      <br>
      <hr> 
          <div class="fb-like" data-href="{{request.build_absolute_uri}}" data-width="" data-layout="standard" data-action="like" data-size="small" data-share="true"></div>   
    </div>
<!-- <a class="btn btn-sm btn-primary" href="{% url 'Comment:add_comment' pk=post.pk %}"> comment</a>

 -->
       {% include 'comments/add_comment.html' with comments=post.comments.all  %}
  <div class=" col-lg-6  border-0 border-danger">
 
        {% for comments in post.comments.all%}
           <div class=" border-faded border-dark">
             <p class="text-default ">{{comments.user}} <small class="text-black-50">{{comments.date|date}}</small></p>
           </div>
          <div class="alert z-depth-1 col-sm-6">
            <p class="text-lowercase">{{comments.content}}</p>
          
          </div>

        {% endfor %}
      </div>

    <div class="jumbotron-fluid down">
        <div class="col-lg-10">
            <div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-numposts="5" data-width=""></div>

        </div>

{% endblock navbar %}

templates/post_list.html
{% extends "base.html" %}
{% block navbar %}
<div class="container-sm ">
<br>
<h1 class="text-center text-bold"> BLOG POSTS</h1>
<hr>
<form >

<div class=" row col-lg-8 ">
    <form  method="get" accept-charset="utf-8" class="form-inline active-cyan-4">
  <input  name="q" value="{{requser.Get.q}}" class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search"
    aria-label="Search">
   <button type="submit" class="btn btn-rounded btn-warning btn-sm search-btn"> <i class="fas fa-search" aria-hidden="true"></i></button>
</form>

</div>
<br>
    {% for post in post_list %}
    <div class="col-lg-6">
        <!-- Card image -->
        <!-- Card content -->
        <div class="card-body z-depth-1">
            <!-- Title -->
            <h4 class="card-title ">
                <h4 class="text-success">
                    <a class="text-capitalize" href="{% url 'Post:detail' pk=post.pk %}">{{post.title}}</a>
                    <hr>
                </h4>
            </h4>
            <!-- Text -->
            <p class="card-text"> {{post.content|truncatechars:180}}</p>
           <p> <i class="text-black-50"> Author : <i class="text-black-4">{{post.user.username}}</></i></p>
            <a href="{% url 'Post:detail' pk=post.pk %}" class="btn btn-primary z-depth-1">view</a>
        </div>
    </div>
    <br>
    {% endfor %}

        <!--Grid row-->
      
            <!--Grid column-->
            <div class="col-md-6 mb-4">
            </div>
            <div class="col-md-6 mb-4">
                <div class="pagination text-dark text-center ">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                        <a class="text-info z-depth-1 btn-link" href="?page=1">&laquo; first</a>
                        <a class="text-info z-depth-1 btn-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}
                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>
                        {% if page_obj.has_next %}
                        <a class="text-info z-depth-1 btn-link" href="?page={{ page_obj.next_page_number }}">next</a>
                        <a class="text-info z-depth-1 btn-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
            <!--Grid column-->
        <!--Grid row-->

<footer class="page-footer font-small special-color-grey pt-4">
    <!-- Footer Elements -->
    
    <!-- Footer Elements -->
    <!-- Copyright -->
    <div class="footer-copyright text-center text-dark py-3 z-depth-2 ">© 2020 Copyright:
        <a href="https://mdbootstrap.com/" class="text-dark"> feelsafe security</a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->
{% endblock navbar %}

templates/post_update.html
{% extends "base.html" %}
{% block navbar %}

<div class="container text-center">
    <div class="jumbotron">
        <h1 class="text-primary"> UPDATE POST</h1>
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update">
        </form>
    </div>
</div>
{% endblock navbar %}